name: AdminUtils
version: 1.0.0
author: ItsWers0n

main: me.itswers0n.AdminUtils

commands:
  gm:
    permission: adminutils.command.gm
    permission-message: "§4You don't have permission to use this command"
    description: "Gamemode changer command."
  fly:
    permission: adminutils.command.fly
    permission-message: "§4You don't have permission to use this command"
    description: "Enables flying abbility for player."
  weatherlock:
    aliases: wlock
    permission: adminutils.command.weatherlock
    permission-message: "§4You don't have permission to use this command"
    description: "Locks and unlocks weather."
  heal:
    permission: adminutils.command.heal
    permission-message: "§4You don't have permission to use this command"
    description: "Heals target player."
  feed:
    permission: adminutils.command.feed
    permission-message: "§4You don't have permission to use this command"
    description: "Feeds target player."
  day:
    permission: adminutils.command.day
    permission-message: "§4You don't have permission to use this command"
    description: "Sets time to day."
  night:
    permission: adminutils.command.night
    permission-message: "§4You don't have permission to use this command"
    description: "Sets time to night."
  repair:
    aliases: fix
    permission: adminutils.command.repair
    permission-message: "§4You don't have permission to use this command"
    description: "Repairs the durability of one or all items."
  multiworld:
    aliases: mw
    permission: adminutils.command.multiworld
    permission-message: "§4You don't have permission to use this command"
    description: "Gives access to creating, loading and travelling to other worlds."